print('It`s really hot!')
print('I said "Hello!" to him.')
print('He said "What`s there?"')
print('Newlne character is \\n, Tab character is \\t.')
print('Working directory is C:\\workspace\\mywork.')